baseURL: "https://example.com"
languageCode: "tr"
title: "apeven's blog"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# settings
paginate: 30
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
